name: rustbin
services:
    rustbin-db:
        container_name: rustbin-db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=rustbin
        ports:
            - 5432:5432
        image: docker.io/library/postgres
    rustbin:
        environment:
            - DATABASE_URL=postgres://postgres:postgres@rustbin-db/rustbin
        ports:
            - 8080:8080
        build:
          dockerfile: Dockerfile